"""HTML reporting utilities for VoidScan."""

from html import escape
from pathlib import Path
from typing import Any


def generate_html_report(report: dict[str, Any]) -> str:
    """Generate a self-contained HTML report from a VoidScan report."""

    result = report.get("result", {})

    scan_type = escape(str(report.get("scan_type", "Unknown")))
    target = escape(str(report.get("target", "Unknown")))
    timestamp = escape(str(report.get("timestamp", "Unknown")))

    status = "Unknown"
    status_class = "unknown"

    if isinstance(result, dict) and "success" in result:
        if result["success"]:
            status = "Success"
            status_class = "success"
        else:
            status = "Failed"
            status_class = "failed"

    result_json = escape(
        str(result)
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VoidScan Report - {target}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background: #f4f4f4;
            color: #222;
            margin: 0;
            padding: 40px;
        }}

        .container {{
            max-width: 1000px;
            margin: auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
        }}

        h1 {{
            margin-top: 0;
        }}

        .metadata {{
            display: grid;
            grid-template-columns: 180px 1fr;
            gap: 10px;
            margin-bottom: 30px;
        }}

        .label {{
            font-weight: bold;
        }}

        .status {{
            font-weight: bold;
        }}

        .success {{
            color: green;
        }}

        .failed {{
            color: red;
        }}

        .unknown {{
            color: #777;
        }}

        pre {{
            background: #111;
            color: #eee;
            padding: 20px;
            overflow-x: auto;
            border-radius: 6px;
        }}

        footer {{
            margin-top: 30px;
            color: #777;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>VoidScan Security Assessment Report</h1>

        <div class="metadata">
            <div class="label">Scan Type</div>
            <div>{scan_type}</div>

            <div class="label">Target</div>
            <div>{target}</div>

            <div class="label">Timestamp</div>
            <div>{timestamp}</div>

            <div class="label">Status</div>
            <div class="status {status_class}">{status}</div>
        </div>

        <h2>Scan Results</h2>

        <pre>{result_json}</pre>

        <footer>
            Generated by VoidScan v0.1.0
        </footer>
    </div>
</body>
</html>
"""


def save_html_report(
    report: dict[str, Any],
    output_directory: Path,
) -> Path:
    """Generate and save a VoidScan HTML report."""

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    scan_type = (
        str(report.get("scan_type", "scan"))
        .lower()
        .replace(" ", "_")
    )

    filename = f"{scan_type}_report.html"
    output_path = output_directory / filename

    output_path.write_text(
        generate_html_report(report),
        encoding="utf-8",
    )

    return output_path